services:
  stock-price-updown-ai:
    build:
      context: .
      dockerfile: ./Docker/stock-price-updown-ai/Dockerfile
    image: python:3.8-slim
    container_name: stock-price-updown-ai
    working_dir: /app/stock-price-updown-ai
    volumes:
      - ../StockPriceUpDownAI:/app/stock-price-updown-ai
      - ../StockPriceUpDownAI/output:/app/stock-price-updown-ai/output
    environment:
      PYTHONUNBUFFERED: 1
    command: python main.py
